### PR TITLE
Add multiple extensions per mimetype support

### PR DESCRIPTION
**Pull request by zayass**
Some mimetypes in http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types have multiple extension

For example very common
```
image/jpeg					jpeg jpg jpe
```

This PR adding support of such things and update generated code

### CODE REVIEW

**Review by rafiki270 — APPROVED** [review]
nice one brother! :) I had no idea anyone is using this haha ...

**Comment by zayass** [comment]
Oh you are so fast :)
I found an issue here

**Comment by rafiki270** [comment]
you are the only one I know using this now so I gave you write access ... please still do PR's so I can see what goes in though :)

**Comment by rafiki270** [comment]
@zayass

**Comment by zayass** [comment]
:)
Ok I'll rebase and rePR when fix it

**Comment by zayass** [comment]
@rafiki270 fixed, rebased, rePRed
see #2

**Pull request merged**
